spring.application.name=DnD_Market_Backend
# ???? ???????
server.port=8080

# H2-???????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / H2
spring.datasource.url=jdbc:h2:mem:marketdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ??? (? ??????)
spring.cache.type=simple
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ??????? URL ??? ???? ???????? ? DarkerDB
darkerdb.base-url=https://api.darkerdb.com/v1

#API-????
darkerdb.api-key=8da7659fa51765d0f7e1
